### ISSUE TITLE
Wrong number of arguments under Ruby 2.0 and Rails 3.2.13

### ISSUE THREAD

**Issue by turadg** [moiristo/deep_cloneable#24]
With Ruby 2.0 and Rails 3.2-STABLE, the :include isn't working:

``` rb
> question.dup :include => :choices
ArgumentError: wrong number of arguments (1 for 0)
```

Maybe it's not removing the original `dup` correctly?

Fwiw, I first thought it was a bug in Rails because even regular `dup` didn't work

``` rb
> p.dup
NoMethodError: private method `initialize_dup' called for #<Question:0x007fd6fb9d9a98>
```

But I just switched updated Rails past [this bug in Rails 3.2.x with Ruby 2.0 that was fixed in 3.12.13](https://github.com/rails/rails/issues/9417).

**Comment by bsutherland** [comment]
I've having this issue with Rails 4.2.3 and deep_cloneable 2.1.1.

The strange thing is, it works when I run service / controller tests from RSpec, but when I run the rails app and send a real request, I get the 'Wrong number of arguments' error.

**Comment by moiristo** [comment]
Can you provide a stacktrace?

**Comment by bsutherland** [comment]
Thanks for the reply. Here's the call and the full backtrace.

Code:

```
  215  next_version = kv.deep_clone(
  216         include: ASSOCIATIONS_FOR_DEEP_CLONE,
  217         except: [:updated_by, :customer_id],
  218         validate: false
  219       )
```

```
Full backtrace
--------------

 - app/services/meta_service.rb:215:in `update_meta'
 - app/controllers/public_api/meta_controller.rb:114:in `update_meta'
 - actionpack (4.2.3) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
 - actionpack (4.2.3) lib/abstract_controller/base.rb:198:in `process_action'
 - actionpack (4.2.3) lib/action_controller/metal/rendering.rb:10:in `process_action'
 - actionpack (4.2.3) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
 - activesupport (4.2.3) lib/active_support/callbacks.rb:115:in `call'
 - activesupport (4.2.3) lib/active_support/callbacks.rb:553:in `block (2 levels) in compile'
 - activesupport (4.2.3) lib/active_support/callbacks.rb:503:in `call'
 - activesupport (4.2.3) lib/active_support/callbacks.rb:88:in `run_callbacks'
 - actionpack (4.2.3) lib/abstract_controller/callbacks.rb:19:in `process_action'
 - actionpack (4.2.3) lib/action_controller/metal/rescue.rb:29:in `process_action'
 - actionpack (4.2.3) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
 - activesupport (4.2.3) lib/active_support/notifications.rb:164:in `block in instrument'
 - activesupport (4.2.3) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
 - activesupport (4.2.3) lib/active_support/notifications.rb:164:in `instrument'
 - actionpack (4.2.3) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
 - actionpack (4.2.3) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
 - activerecord (4.2.3) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
 - actionpack (4.2.3) lib/abstract_controller/base.rb:137:in `process'
 - actionview (4.2.3) lib/action_view/rendering.rb:30:in `process'
 - actionpack (4.2.3) lib/action_controller/metal.rb:196:in `dispatch'
 - actionpack (4.2.3) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
 - actionpack (4.2.3) lib/action_controller/metal.rb:237:in `block in action'
 - actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:76:in `dispatch'
 - actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:45:in `serve'
 - actionpack (4.2.3) lib/action_dispatch/journey/router.rb:43:in `block in serve'
 - actionpack (4.2.3) lib/action_dispatch/journey/router.rb:30:in `serve'
 - actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:821:in `call'
 - bullet (4.14.4) lib/bullet/rack.rb:10:in `call'
 - rack (1.6.4) lib/rack/etag.rb:24:in `call'
 - rack (1.6.4) lib/rack/conditionalget.rb:38:in `call'
 - rack (1.6.4) lib/rack/head.rb:13:in `call'
 - actionpack (4.2.3) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
 - actionpack (4.2.3) lib/action_dispatch/middleware/flash.rb:260:in `call'
 - rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
 - rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
 - actionpack (4.2.3) lib/action_dispatch/middleware/cookies.rb:560:in `call'
 - activerecord (4.2.3) lib/active_record/query_cache.rb:36:in `call'
 - activerecord-refresh_connection (0.0.5) lib/activerecord-refresh_connection/active_record/connection_adapters/refresh_connection_management.rb:17:in `call'
 - activerecord (4.2.3) lib/active_record/migration.rb:377:in `call'
 - actionpack (4.2.3) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
 - activesupport (4.2.3) lib/active_support/callbacks.rb:84:in `run_callbacks'
 - actionpack (4.2.3) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
 - actionpack (4.2.3) lib/action_dispatch/middleware/reloader.rb:73:in `call'
 - actionpack (4.2.3) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
 - better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
 - better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
 - better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
 - actionpack (4.2.3) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
 - actionpack (4.2.3) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
 - railties (4.2.3) lib/rails/rack/logger.rb:38:in `call_app'
 - railties (4.2.3) lib/rails/rack/logger.rb:20:in `block in call'
 - activesupport (4.2.3) lib/active_support/tagged_logging.rb:68:in `block in tagged'
 - activesupport (4.2.3) lib/active_support/tagged_logging.rb:26:in `tagged'
 - activesupport (4.2.3) lib/active_support/tagged_logging.rb:68:in `tagged'
 - railties (4.2.3) lib/rails/rack/logger.rb:20:in `call'
 - request_store (1.1.0) lib/request_store/middleware.rb:8:in `call'
 - actionpack (4.2.3) lib/action_dispatch/middleware/request_id.rb:21:in `call'
 - rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
 - rack (1.6.4) lib/rack/runtime.rb:18:in `call'
 - activesupport (4.2.3) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
 - rack (1.6.4) lib/rack/lock.rb:17:in `call'
 - actionpack (4.2.3) lib/action_dispatch/middleware/static.rb:116:in `call'
 - rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
 - railties (4.2.3) lib/rails/engine.rb:518:in `call'
 - railties (4.2.3) lib/rails/application.rb:165:in `call'
 - rack (1.6.4) lib/rack/content_length.rb:15:in `call'
 - thin (1.6.3) lib/thin/connection.rb:86:in `block in pre_process'
 - thin (1.6.3) lib/thin/connection.rb:84:in `pre_process'
 - thin (1.6.3) lib/thin/connection.rb:53:in `process'
 - thin (1.6.3) lib/thin/connection.rb:39:in `receive_data'
 - eventmachine (1.0.7) lib/eventmachine.rb:187:in `run'
 - thin (1.6.3) lib/thin/backends/base.rb:73:in `start'
 - thin (1.6.3) lib/thin/server.rb:162:in `start'
 - rack (1.6.4) lib/rack/handler/thin.rb:19:in `run'
 - rack (1.6.4) lib/rack/server.rb:286:in `start'
 - railties (4.2.3) lib/rails/commands/server.rb:80:in `start'
 - railties (4.2.3) lib/rails/commands/commands_tasks.rb:80:in `block in server'
 - railties (4.2.3) lib/rails/commands/commands_tasks.rb:75:in `server'
 - railties (4.2.3) lib/rails/commands/commands_tasks.rb:39:in `run_command!'
 - railties (4.2.3) lib/rails/commands.rb:17:in `<top (required)>'
 - bin/rails:4:in `<top (required)>'
 - spring (1.3.6) lib/spring/client/rails.rb:28:in `call'
 - spring (1.3.6) lib/spring/client/command.rb:7:in `call'
 - spring (1.3.6) lib/spring/client.rb:26:in `run'
 - spring (1.3.6) bin/spring:48:in `<top (required)>'
 - /Users/b-sutherland/.rbenv/versions/2.2.0/bin/spring:23:in `<main>'
```

**Comment by moiristo** [comment]
Thanks, I'll let the developer of sexp_processor know of this conflict.
